# Generated by Django 3.0.8 on 2021-03-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201203_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
