# Generated by Django 3.0.8 on 2021-03-28 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210301_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_business_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_physical_store',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99999999", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
