# Generated by Django 3.0.8 on 2021-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210328_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(max_length=9),
        ),
    ]
