# Generated by Django 3.0.8 on 2021-04-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogpost_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='content_initial',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_conclusion',
            field=models.TextField(default='middle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_middle',
            field=models.TextField(default='conclusion'),
            preserve_default=False,
        ),
    ]
