# Generated by Django 3.0.8 on 2021-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hindicontent',
            name='language',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
