# Generated by Django 3.0.8 on 2021-06-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_hindicontent_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HindiContent',
            new_name='Content',
        ),
    ]
