# Generated by Django 3.0.8 on 2021-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210612_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='heading',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='instructions',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
