# Generated by Django 3.0.8 on 2021-03-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_auto_20210218_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storedetails',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
