# Generated by Django 3.0.8 on 2021-03-01 03:45

import app_global.validator
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_auto_20210301_0915'),
        ('products', '0003_productsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(blank=True, upload_to='static/images', validators=[app_global.validator.check_thumbnail])),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image_side1', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('img_path', models.CharField(blank=True, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('qrcode_text', models.CharField(blank=True, max_length=250, null=True)),
                ('product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductSubCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarmentClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='garment',
            name='category',
        ),
        migrations.AddField(
            model_name='garment',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='garment',
            name='image_side1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='garment',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='garment',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductSubCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garment',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='qrcode_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='store',
            field=models.ManyToManyField(to='stores.Store'),
        ),
        migrations.CreateModel(
            name='StationeryItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('primary_color', models.CharField(max_length=30)),
                ('other_colors', models.CharField(max_length=150)),
                ('material', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20)),
                ('colors_available', models.CharField(blank=True, max_length=200, null=True)),
                ('stationery_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsFitnessEquipmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('primary_color', models.CharField(max_length=30)),
                ('other_colors', models.CharField(max_length=150)),
                ('material', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20)),
                ('colors_available', models.CharField(blank=True, max_length=200, null=True)),
                ('sports_fitness_equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('primary_color', models.CharField(max_length=30)),
                ('other_colors', models.CharField(max_length=150)),
                ('material', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20)),
                ('colors_available', models.CharField(blank=True, max_length=200, null=True)),
                ('kitchen_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeDecorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('primary_color', models.CharField(max_length=30)),
                ('other_colors', models.CharField(max_length=150)),
                ('material', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20)),
                ('colors_available', models.CharField(blank=True, max_length=200, null=True)),
                ('HomeDecor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeApplianceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('primary_color', models.CharField(max_length=30)),
                ('other_colors', models.CharField(max_length=150)),
                ('material', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20)),
                ('colors_available', models.CharField(blank=True, max_length=200, null=True)),
                ('home_appliance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('primary_color', models.CharField(max_length=30)),
                ('other_colors', models.CharField(max_length=150)),
                ('material', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20)),
                ('colors_available', models.CharField(blank=True, max_length=200, null=True)),
                ('pockets_qty', models.IntegerField(blank=True, default=1)),
                ('description', models.TextField(blank=True)),
                ('neck_design', models.CharField(choices=[('Round', 'Round'), ('V-neck', 'V-neck'), ('PoloCollar', 'PoloCollar'), ('NA', 'Not Applicable')], default='Round', max_length=20)),
                ('design_pattern', multiselectfield.db.fields.MultiSelectField(choices=[('Checks', 'Checks'), ('Floral', 'Floral'), ('Stripes', 'Stripes'), ('Plain', 'Plain'), ('Prints', 'Prints'), ('Dots', 'Dots'), ('Logos', 'Logos'), ('Slogans', 'Slogans'), ('Others', 'Others')], max_length=60)),
                ('sizes_available', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=17)),
                ('garment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Garment')),
            ],
            options={
                'verbose_name_plural': 'GarmentDetails',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductIdentity'),
        ),
        migrations.AddField(
            model_name='article',
            name='store',
            field=models.ManyToManyField(to='stores.Store'),
        ),
        migrations.AddField(
            model_name='garment',
            name='product_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductIdentity'),
            preserve_default=False,
        ),
    ]
