# Generated by Django 3.0.8 on 2021-03-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210301_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_back',
            new_name='image_rear',
        ),
        migrations.RenameField(
            model_name='garment',
            old_name='image_back',
            new_name='image_rear',
        ),
        migrations.AlterField(
            model_name='garmentdetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='garmentdetails',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='garmentdetails',
            name='other_colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='garmentdetails',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='homeappliancedetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='homeappliancedetails',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='homeappliancedetails',
            name='other_colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homeappliancedetails',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='homedecordetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='homedecordetails',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='homedecordetails',
            name='other_colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homedecordetails',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenitemdetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenitemdetails',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenitemdetails',
            name='other_colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenitemdetails',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportsfitnessequipmentdetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sportsfitnessequipmentdetails',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sportsfitnessequipmentdetails',
            name='other_colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sportsfitnessequipmentdetails',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stationeryitemdetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stationeryitemdetails',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stationeryitemdetails',
            name='other_colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stationeryitemdetails',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='ArticleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('primary_color', models.CharField(max_length=30)),
                ('other_colors', models.CharField(blank=True, max_length=150, null=True)),
                ('material', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(blank=True, default=False, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20)),
                ('colors_available', models.CharField(blank=True, max_length=200, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
