# Generated by Django 3.0.8 on 2021-03-07 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210308_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_field',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articledetails',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='articledetails',
            name='origin_country',
            field=models.CharField(blank=True, default='INDIA', max_length=50),
        ),
        migrations.AddField(
            model_name='garmentdetails',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='garmentdetails',
            name='origin_country',
            field=models.CharField(blank=True, default='INDIA', max_length=50),
        ),
        migrations.AddField(
            model_name='homeappliancedetails',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homeappliancedetails',
            name='origin_country',
            field=models.CharField(blank=True, default='INDIA', max_length=50),
        ),
        migrations.AddField(
            model_name='homedecordetails',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homedecordetails',
            name='origin_country',
            field=models.CharField(blank=True, default='INDIA', max_length=50),
        ),
        migrations.AddField(
            model_name='kitchenitemdetails',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kitchenitemdetails',
            name='origin_country',
            field=models.CharField(blank=True, default='INDIA', max_length=50),
        ),
        migrations.AddField(
            model_name='sportsfitnessequipmentdetails',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportsfitnessequipmentdetails',
            name='origin_country',
            field=models.CharField(blank=True, default='INDIA', max_length=50),
        ),
        migrations.AddField(
            model_name='stationeryitemdetails',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stationeryitemdetails',
            name='origin_country',
            field=models.CharField(blank=True, default='INDIA', max_length=50),
        ),
        migrations.AlterField(
            model_name='garmentdetails',
            name='garment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Article'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='clothing',
            field=models.ManyToManyField(to='products.Article'),
        ),
        migrations.DeleteModel(
            name='Garment',
        ),
    ]
