# Generated by Django 3.0.8 on 2021-03-28 12:22

import app_global.validator
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210308_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_upload_path, validators=[app_global.validator.check_thumbnail]),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_rear',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_side1',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_upload_path),
        ),
    ]
